"""Abstract container backend interface.

WayDroid Toolkit uses this interface for all container lifecycle operations
so that the LXC and Incus backends are interchangeable from the perspective
of every module above core/.

Scope of this abstraction
--------------------------
This covers only the operations WayDroid Toolkit performs directly:
  - querying container state
  - starting / stopping the container
  - executing commands inside the container
  - checking whether the backend binary is present

It does NOT attempt to abstract the Android-specific device node configuration
that lives inside upstream waydroid/waydroid (tools/helpers/lxc.py). That
configuration is generated by the waydroid daemon itself and is outside the
scope of this toolkit.
"""

from __future__ import annotations

import subprocess
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum


class BackendType(Enum):
    LXC = "lxc"
    INCUS = "incus"


class ContainerState(Enum):
    RUNNING = "running"
    STOPPED = "stopped"
    FROZEN = "frozen"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class BackendInfo:
    backend_type: BackendType
    binary: str           # e.g. "lxc-start" or "incus"
    version: str          # raw version string from the binary
    container_name: str   # e.g. "waydroid"


class ContainerBackend(ABC):
    """Interface every container backend must implement."""

    CONTAINER_NAME = "waydroid"

    # ── Identity ──────────────────────────────────────────────────────────────

    @property
    @abstractmethod
    def backend_type(self) -> BackendType:
        ...

    @abstractmethod
    def is_available(self) -> bool:
        """Return True if the backend binary is present on PATH."""
        ...

    @abstractmethod
    def get_info(self) -> BackendInfo:
        """Return version and identity information for this backend."""
        ...

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    @abstractmethod
    def start(self) -> None:
        """Start the Waydroid container."""
        ...

    @abstractmethod
    def stop(self, timeout: int = 10) -> None:
        """Stop the Waydroid container."""
        ...

    @abstractmethod
    def freeze(self) -> None:
        """Freeze (pause) the container."""
        ...

    @abstractmethod
    def unfreeze(self) -> None:
        """Unfreeze (resume) the container."""
        ...

    # ── Introspection ─────────────────────────────────────────────────────────

    @abstractmethod
    def get_state(self) -> ContainerState:
        """Return the current container state."""
        ...

    # ── Execution ─────────────────────────────────────────────────────────────

    @abstractmethod
    def execute(
        self,
        cmd: list[str],
        timeout: int = 30,
    ) -> subprocess.CompletedProcess[str]:
        """Run cmd inside the container, returning the completed process."""
        ...

    # ── Snapshots ─────────────────────────────────────────────────────────────

    @abstractmethod
    def snapshot_create(self, name: str) -> None:
        """Create a named snapshot of the container."""
        ...

    @abstractmethod
    def snapshot_list(self) -> list[str]:
        """Return snapshot names for the container."""
        ...

    @abstractmethod
    def snapshot_restore(self, name: str) -> None:
        """Restore the container to a named snapshot."""
        ...

    @abstractmethod
    def snapshot_delete(self, name: str) -> None:
        """Delete a named snapshot."""
        ...

    # ── Console ───────────────────────────────────────────────────────────────

    @abstractmethod
    def console(self) -> None:
        """Attach to the container console interactively (replaces the process)."""
        ...
