"""wdt config — manage wdt configuration file.

The config file lives at ~/.config/waydroid-toolkit/config.yaml.

Sub-commands
------------
  wdt config show    Print the current configuration
  wdt config edit    Open the config file in $EDITOR
  wdt config init    Write a default config file (non-destructive)
  wdt config path    Print the config file path
  wdt config set     Set a key=value pair
  wdt config get     Get the value of a key
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import click
from rich.console import Console
from rich.syntax import Syntax

console = Console()

_CONFIG_DIR = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "waydroid-toolkit"
_CONFIG_FILE = _CONFIG_DIR / "config.yaml"

_DEFAULT_CONFIG = """\
# waydroid-toolkit configuration
# Generated by: wdt config init

# Container backend: incus | lxc | auto
backend: auto

# Default backup directory
backup_dir: ~/.local/share/waydroid-toolkit/backups

# Fleet: filter instances by name prefix (empty = all containers)
fleet_prefix: ""

# Shell: default shell binary inside the container
shell: /bin/bash

# Logging level: debug | info | warning | error
log_level: info
"""


def _load_yaml(path: Path) -> dict:
    try:
        import yaml  # type: ignore[import-untyped]
        with path.open() as fh:
            return yaml.safe_load(fh) or {}
    except ImportError:
        # Fallback: very simple key: value parser (no nesting)
        data: dict = {}
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and ":" in line:
                k, _, v = line.partition(":")
                data[k.strip()] = v.strip().strip('"')
        return data


def _save_yaml(path: Path, data: dict) -> None:
    try:
        import yaml  # type: ignore[import-untyped]
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w") as fh:
            yaml.dump(data, fh, default_flow_style=False, allow_unicode=True)
    except ImportError:
        # Fallback: rewrite as simple key: value
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = []
        for k, v in data.items():
            lines.append(f"{k}: {v}")
        path.write_text("\n".join(lines) + "\n")


@click.group("config")
def cmd() -> None:
    """Manage wdt configuration."""


@cmd.command("show")
def config_show() -> None:
    """Print the current configuration file."""
    if not _CONFIG_FILE.exists():
        console.print(f"[yellow]No config file found at {_CONFIG_FILE}[/yellow]")
        console.print("Create one with: wdt config init")
        return
    text = _CONFIG_FILE.read_text()
    console.print(Syntax(text, "yaml", theme="monokai", line_numbers=True))


@cmd.command("edit")
def config_edit() -> None:
    """Open the config file in $EDITOR."""
    if not _CONFIG_FILE.exists():
        _CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        _CONFIG_FILE.write_text(_DEFAULT_CONFIG)
        console.print(f"[cyan]Created default config at {_CONFIG_FILE}[/cyan]")

    editor = os.environ.get("EDITOR", os.environ.get("VISUAL", "nano"))
    subprocess.run([editor, str(_CONFIG_FILE)])


@cmd.command("init")
@click.option("--force", is_flag=True, help="Overwrite existing config.")
def config_init(force: bool) -> None:
    """Write a default config file.

    Does nothing if the file already exists unless --force is given.
    """
    if _CONFIG_FILE.exists() and not force:
        console.print(f"[yellow]Config already exists:[/yellow] {_CONFIG_FILE}")
        console.print("Use --force to overwrite.")
        return
    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    _CONFIG_FILE.write_text(_DEFAULT_CONFIG)
    console.print(f"[green]Config written to:[/green] {_CONFIG_FILE}")


@cmd.command("path")
def config_path() -> None:
    """Print the config file path."""
    console.print(str(_CONFIG_FILE))


@cmd.command("get")
@click.argument("key")
def config_get(key: str) -> None:
    """Get the value of KEY from the config file."""
    if not _CONFIG_FILE.exists():
        console.print("[yellow]No config file. Run: wdt config init[/yellow]")
        raise SystemExit(1)
    data = _load_yaml(_CONFIG_FILE)
    if key not in data:
        console.print(f"[red]Key not found:[/red] {key}")
        raise SystemExit(1)
    console.print(data[key])


@cmd.command("set")
@click.argument("key")
@click.argument("value")
def config_set(key: str, value: str) -> None:
    """Set KEY to VALUE in the config file.

    \b
    Examples:
      wdt config set backend incus
      wdt config set log_level debug
    """
    if not _CONFIG_FILE.exists():
        _CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        _CONFIG_FILE.write_text(_DEFAULT_CONFIG)

    data = _load_yaml(_CONFIG_FILE)
    data[key] = value
    _save_yaml(_CONFIG_FILE, data)
    console.print(f"[green]Set[/green] {key} = {value}")
